[project]
name = "stac-lake"
version = "0.1.0"
description = "STAC-powered data lake for geospatial rasters."
readme = "README.md"
requires-python = ">=3.10"
dependencies = []

[build-system]
requires = ["hatchling >= 1.26"]
build-backend = "hatchling.build"